name: Github Actions 실행하기

on:
  push:
    branches:
      - main

jobs:
  My-First-CICD-Job:
    runs-on: ubuntu-latest

    steps:
      - name: simple-web
        run: echo "This is the first cicd step"

      - name: test-1
        run: |
          pwd
          ls -al

      - name: 파일 생성
        run: echo "hello world" > test.txt

      - name: test-2
        run: |
          ls -al
          cat test.txt

      - name: Github Variables 사용하기
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY

      - name: Github Secret Variables 사용하기
        run: |
          echo ${{secrets.MY_ENV_NAME}}
          echo ${{secrets.MY_ENV_PASSWORD}}